# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: Update package cache RedHat
      tags: always
      dnf: update_cache=yes
      changed_when: False
      when: ansible_os_family == "RedHat"
    - name: Upgrade all packages RedHat
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
    - name: Update package cache Debian
      tags: always
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      changed_when: False
      when: ansible_os_family == "Debian"
    - name: Upgrade all packages Debian
      apt: upgrade=dist force_apt_get=yes
      when: ansible_os_family == "Debian"

# run roles
- hosts: all
  tags: base
  become: true
  roles:

- hosts: proxmox
  tags: proxmox
  become: true
  roles:

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - gnupg
    - vscode
    - users

- hosts: server
  tags: server
  become: true
  roles:
    - cockpit
    - telegraf
    - certbot

- hosts: serverdomaincontroller
  tags: serverdomaincontroller
  become: true
  roles:

- hosts: servermonitoring
  tags: servermonitoring
  become: true
  roles:
    - influxdb
    - grafana

- hosts: serverpostgresql
  tags: serverpostgresql
  become: true
  roles:
    # - pgadmin

# end of run cleanup and reporting
- hosts: all
  become: true
  tasks:
  - name: Post-run | Remove orphan packages
    tags: always
    dnf:
      autoremove: yes
    when: ansible_os_family == "RedHat"

  - name: Post-run | Send completion alert
    include_tasks: playbooks/send_completion_alert.yml
    tags: always
    when:
      - task_failed is not defined

  - name: Post-run | Send failure alert
    include_tasks: playbooks/send_failure_alert.yml
    tags: always
    when:
      - task_failed is defined
      - task_failed == true
